// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATlDzKYy3pT96Bh8XUaBXSmJeJccxbyRc',
    appId: '1:654069731109:web:2d1b7bfcb8d4836f5a14cc',
    messagingSenderId: '654069731109',
    projectId: 'pit-stop-6e8ad',
    authDomain: 'pit-stop-6e8ad.firebaseapp.com',
    databaseURL: 'https://pit-stop-6e8ad-default-rtdb.firebaseio.com',
    storageBucket: 'pit-stop-6e8ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpXmEB64pvQnK9OP5aqHKXi0Bw6clMXP0',
    appId: '1:654069731109:android:0b14344fde169c155a14cc',
    messagingSenderId: '654069731109',
    projectId: 'pit-stop-6e8ad',
    databaseURL: 'https://pit-stop-6e8ad-default-rtdb.firebaseio.com',
    storageBucket: 'pit-stop-6e8ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwx8jplHMdaRuIZHtGMSFl6CsL4DCRfBQ',
    appId: '1:654069731109:ios:dc3db6fe6cb46c6c5a14cc',
    messagingSenderId: '654069731109',
    projectId: 'pit-stop-6e8ad',
    databaseURL: 'https://pit-stop-6e8ad-default-rtdb.firebaseio.com',
    storageBucket: 'pit-stop-6e8ad.firebasestorage.app',
    iosBundleId: 'com.example.pitStop',
  );
}
